apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echo.fullname" . }}-configuration
data:
  default.yml: |-
    {{ .Files.Get "files/default.yml"|nindent 4 }}
    url: {{ .Values.url }}